public enum BattleActionType
{
    EndTurn,
    PlaceBroadcast,
    StartMainGame,
    SummonFaceUp,
    SummonFaceDown,
    FlipSummon,
    MoveCharacter,
    StartCollab,
    UseContent,
    UseCharacterActive,
    UseIdolActive,
    SelectEffectTarget,
    SelectCardOption,
    SelectMultipleCardOptions,
    SelectEffectChoice,
    Surrender
}
